version: '3'
services:
  app:
    build: .
    ports:
      - "8090:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: "redis:latest"
